- name: loops Demo
  hosts: all
  connection: local
  tasks:
    - name: print fruit name
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - bannana
        - orange
        - grape
        - papaya
        - muskmelon

    - name: print fruit name with quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, quantity - {{ item.quantity }}
      loop:
        - { name: apple, quantity: 100}
        - { name: bannana, quantity: 100}
        - { name: orange, quantity: 100}
        - { name: grape, quantity: 100}
        - { name: papaya, quantity: 100}
        - { name: muskmelon, quantity: 100}