- name: loops Demo
  hosts: all
  connection: local
  tasks:
    - name: print fruit name
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - bannana
        - orange
        - grape
        - papaya
        - muskmelon