- name: Demo to load another playbook
  hosts: all
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: Message by ansible builtin debug module

    - name: Include another yaml file common.yml
      ansible.builtin.include_tasks:
        file: common.yml